#!/usr/bin/env python3
"""Preview or initialize a portable single-machine RKF workspace.

The default invocation is read-only. Use --apply for a new checkout. Existing
workspace or connector configuration files are never overwritten.
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rkf.core import Workspace


CODEX_SKILL_NAME = "rkf-auto-connect"
CODEX_SKILL_FILES = (Path("SKILL.md"), Path("agents/openai.yaml"))
CODEX_SKILL_DIRS = (Path("agents"),)
CODEX_SKILL_MANIFEST = {
    **{path: "file" for path in CODEX_SKILL_FILES},
    **{path: "directory" for path in CODEX_SKILL_DIRS},
}


def opaque_machine_id() -> str:
    return f"machine-{secrets.token_hex(4)}"


def render_workspace_config(
    *,
    machine_id: str,
    wiki_root: str = ".rkf_data/wiki",
    raw_root: str = ".rkf_data/raw",
    private_evidence_root: str = ".rkf_private/evidence",
) -> str:
    wiki_value = json.dumps(wiki_root, ensure_ascii=False)
    raw_value = json.dumps(raw_root, ensure_ascii=False)
    private_value = json.dumps(private_evidence_root, ensure_ascii=False)
    machine_value = json.dumps(machine_id, ensure_ascii=False)
    return f'''# Generated by tools/bootstrap_rkf.py for one local machine.
# This ignored file may contain machine-specific paths. Do not commit it.

[storage]
wiki_root = {wiki_value}
raw_root = {raw_value}
private_evidence_root = {private_value}

[machine]
id = {machine_value}
maintenance_writer = true

[sync]
writer_registry = "state/sync/maintenance-writer.json"
atomic_writes = true
conflict_detection = true
aggregate_cadence_hours = 24

[gates]
require_pdf_checkpoint = true
require_pdf_qc = true
require_claim_support = true
require_synthesis_review = true

[knowledge]
schema_version = "rkf-v1.1"
default_review_cadence = "monthly"
'''


def render_connector_config(repo_root: Path) -> str:
    root_value = json.dumps(repo_root.resolve().as_posix(), ensure_ascii=False)
    return (
        "# Machine-local RKF connector config. Do not commit.\n\n"
        "[researchwiki]\n"
        f"root = {root_value}\n\n"
        "[policy]\n"
        'mode = "active-aggressive"\n'
    )


def _storage_target(repo_root: Path, value: str) -> tuple[Path, Path, bool]:
    """Return the lexical/resolved target and whether a relative path traverses up."""

    configured = Path(os.path.expandvars(os.path.expanduser(value)))
    is_relative = not configured.is_absolute()
    traverses_up = is_relative and ".." in configured.parts
    lexical = repo_root / configured if is_relative else configured
    resolved = lexical if lexical.is_symlink() else lexical.resolve()
    return lexical, resolved, traverses_up


def _nonempty(path: Path) -> bool:
    try:
        return path.exists() and (not path.is_dir() or any(path.iterdir()))
    except OSError:
        return True


def _paths_overlap(first: Path, second: Path) -> bool:
    for candidate, parent in ((first, second), (second, first)):
        try:
            candidate.relative_to(parent)
            return True
        except ValueError:
            continue
    return False


def _mkdir_tracked(path: Path, created_dirs: list[Path]) -> None:
    """Create one directory chain while recording only directories created here."""

    if path.is_symlink():
        raise OSError("refusing to create through a symlink directory target")
    if path.exists():
        if not path.is_dir():
            raise OSError("directory target is occupied by a non-directory")
        return
    missing: list[Path] = []
    cursor = path
    while not cursor.exists() and not cursor.is_symlink():
        missing.append(cursor)
        if cursor.parent == cursor:
            break
        cursor = cursor.parent
    if cursor.is_symlink() or not cursor.is_dir():
        raise OSError("directory parent is unsafe or unavailable")
    for candidate in reversed(missing):
        try:
            candidate.mkdir()
        except FileExistsError:
            if candidate.is_symlink() or not candidate.is_dir():
                raise OSError("directory target changed during creation")
        else:
            created_dirs.append(candidate)


def _write_new_text(
    path: Path,
    text: str,
    *,
    created_dirs: list[Path] | None = None,
) -> bytes:
    if path.exists() or path.is_symlink():
        raise SystemExit("bootstrap refuses to overwrite or follow an existing config target")
    tracked = created_dirs if created_dirs is not None else []
    _mkdir_tracked(path.parent, tracked)
    payload = text.encode("utf-8")
    created = False
    try:
        with path.open("xb") as handle:
            created = True
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        if created and path.is_file() and not path.is_symlink():
            try:
                path.unlink()
            except OSError:
                pass
        raise
    return payload


def _safe_regular_file(path: Path) -> bool:
    return path.is_file() and not path.is_symlink()


def _parent_can_host(target: Path) -> bool:
    """Return whether ``target`` can be created without traversing a file parent."""

    parent = target.parent
    if parent.is_symlink():
        return False
    probe = parent
    while not probe.exists():
        if probe.is_symlink():
            return False
        if probe.parent == probe:
            return False
        probe = probe.parent
    return (
        not probe.is_symlink()
        and probe.is_dir()
        and os.access(probe, os.W_OK | os.X_OK)
    )


def _directory_can_host_children(path: Path) -> bool:
    if path.is_symlink():
        return False
    if path.exists():
        return path.is_dir() and os.access(path, os.W_OK | os.X_OK)
    return _parent_can_host(path)


def _skill_tree_manifest(root: Path) -> dict[Path, str] | None:
    """Return a no-follow manifest, or ``None`` for unsafe/unreadable trees."""

    if root.is_symlink() or not root.is_dir():
        return None
    manifest: dict[Path, str] = {}
    pending = [root]
    try:
        while pending:
            directory = pending.pop()
            for child in directory.iterdir():
                relative = child.relative_to(root)
                if child.is_symlink():
                    manifest[relative] = "symlink"
                elif child.is_dir():
                    manifest[relative] = "directory"
                    pending.append(child)
                elif child.is_file():
                    manifest[relative] = "file"
                else:
                    manifest[relative] = "other"
    except OSError:
        return None
    return manifest


def _exact_skill_manifest(root: Path) -> bool:
    return _skill_tree_manifest(root) == CODEX_SKILL_MANIFEST


def _skill_bundle_status(source_dir: Path, target_dir: Path) -> str:
    source_files = [source_dir / relative for relative in CODEX_SKILL_FILES]
    if not _exact_skill_manifest(source_dir) or not all(
        _safe_regular_file(path) for path in source_files
    ):
        return "source-invalid"
    if not target_dir.exists() and not target_dir.is_symlink():
        return "would-create"
    if not _exact_skill_manifest(target_dir):
        return "existing-unverified"
    target_files = [target_dir / relative for relative in CODEX_SKILL_FILES]
    if not all(_safe_regular_file(path) for path in target_files):
        return "existing-unverified"
    try:
        return (
            "existing-matching"
            if all(
                source.read_bytes() == target.read_bytes()
                for source, target in zip(source_files, target_files)
            )
            else "existing-unverified"
        )
    except OSError:
        return "existing-unverified"


def _remove_created_skill_tree(path: Path, source_dir: Path | None = None) -> None:
    """Remove only the known skill tree created by this invocation."""

    if path.is_symlink() or not path.is_dir():
        return
    if source_dir is not None and _skill_bundle_status(source_dir, path) != "existing-matching":
        return
    for relative in reversed(CODEX_SKILL_FILES):
        target = path / relative
        if target.is_file() and not target.is_symlink():
            try:
                target.unlink()
            except OSError:
                return
    for relative in sorted(CODEX_SKILL_DIRS, key=lambda item: len(item.parts), reverse=True):
        try:
            (path / relative).rmdir()
        except OSError:
            return
    try:
        path.rmdir()
    except OSError:
        pass


def _install_skill_bundle(
    source_dir: Path,
    target_dir: Path,
    *,
    created_dirs: list[Path] | None = None,
) -> tuple[str, bool]:
    initial_status = _skill_bundle_status(source_dir, target_dir)
    if initial_status == "source-invalid":
        raise OSError("repository skill source changed after preflight")
    if initial_status not in {"would-create", "existing-matching"}:
        return initial_status, False
    if initial_status == "existing-matching":
        return initial_status, False
    if not _parent_can_host(target_dir):
        raise OSError("skill target parent is not writable")
    parent_dirs = created_dirs if created_dirs is not None else []
    parent_start = len(parent_dirs)
    _mkdir_tracked(target_dir.parent, parent_dirs)
    stage = Path(
        tempfile.mkdtemp(prefix=f".{target_dir.name}.rkf-stage-", dir=target_dir.parent)
    )
    installed = False
    try:
        (stage / "agents").mkdir()
        for relative in CODEX_SKILL_FILES:
            source = source_dir / relative
            target = stage / relative
            with target.open("xb") as handle:
                handle.write(source.read_bytes())
                handle.flush()
                os.fsync(handle.fileno())
        if _skill_bundle_status(source_dir, stage) != "existing-matching":
            raise OSError("staged skill bundle failed exact verification")
        if target_dir.exists() or target_dir.is_symlink():
            raise OSError("skill target changed during installation")
        stage.rename(target_dir)
        installed = True
        return "created", True
    finally:
        if not installed:
            _remove_created_skill_tree(stage)
            if created_dirs is None:
                for directory in reversed(parent_dirs[parent_start:]):
                    try:
                        directory.rmdir()
                    except OSError:
                        pass


def _remove_created_file(path: Path, expected: bytes) -> None:
    if path.is_symlink() or not path.is_file():
        return
    try:
        if path.read_bytes() == expected:
            path.unlink()
    except OSError:
        return


def _rollback_created(
    *,
    files: list[tuple[Path, bytes]],
    dirs: list[Path],
    skill_target: Path | None,
    skill_source: Path,
) -> None:
    for path, expected in reversed(files):
        _remove_created_file(path, expected)
    if skill_target is not None:
        _remove_created_skill_tree(skill_target, skill_source)
    for directory in reversed(dirs):
        try:
            directory.rmdir()
        except OSError:
            pass


def bootstrap_local(
    repo_root: Path,
    *,
    apply: bool = False,
    install_connector: bool = False,
    connector_path: Path | None = None,
    codex_skill_dir: Path | None = None,
    wiki_root: str = ".rkf_data/wiki",
    raw_root: str = ".rkf_data/raw",
    private_evidence_root: str = ".rkf_private/evidence",
) -> dict[str, Any]:
    requested_root = repo_root.expanduser()
    if not requested_root.is_dir():
        raise SystemExit("bootstrap repo root must be an existing directory")
    try:
        root = requested_root.resolve()
    except (OSError, RuntimeError) as error:
        raise SystemExit("bootstrap repo root could not be resolved safely") from error
    workspace_config = root / "rkf.workspace.toml"
    connector = (connector_path or Path("~/.codex/rkf_connector.toml")).expanduser()
    skill_source = root / "skills" / CODEX_SKILL_NAME
    skill_target = (
        codex_skill_dir
        or Path(f"~/.codex/skills/{CODEX_SKILL_NAME}")
    ).expanduser()
    workspace_exists = workspace_config.exists()
    connector_exists = connector.exists()
    blockers: list[str] = []
    if workspace_config.is_symlink():
        blockers.append("WORKSPACE_CONFIG_SYMLINK")
    elif workspace_exists and not workspace_config.is_file():
        blockers.append("WORKSPACE_CONFIG_INVALID")
    elif not workspace_exists and not _parent_can_host(workspace_config):
        blockers.append("WORKSPACE_PARENT_INVALID")
    if install_connector and connector.is_symlink():
        blockers.append("CONNECTOR_CONFIG_SYMLINK")
    elif install_connector and connector_exists and not connector.is_file():
        blockers.append("CONNECTOR_TARGET_INVALID")
    if install_connector:
        if not connector_exists and not _parent_can_host(connector):
            blockers.append("CONNECTOR_PARENT_INVALID")
        if not _exact_skill_manifest(skill_source):
            blockers.append("CODEX_SKILL_SOURCE_INVALID")
        if not skill_target.exists() and not skill_target.is_symlink() and not _parent_can_host(skill_target):
            blockers.append("CODEX_SKILL_PARENT_INVALID")
        if skill_target.is_symlink() or (skill_target.exists() and not skill_target.is_dir()):
            blockers.append("CODEX_SKILL_TARGET_INVALID")
        elif skill_target.exists() and not _exact_skill_manifest(skill_target):
            blockers.append("CODEX_SKILL_TARGET_MANIFEST_INVALID")

    storage_targets: dict[str, Path] = {}
    storage_lexical: dict[str, Path] = {}
    overlaps: list[str] = []
    occupied: list[str] = []
    if not workspace_exists and not workspace_config.is_symlink():
        traversal_found = False
        invalid_path_found = False
        for name, value in {
            "wiki_root": wiki_root,
            "raw_root": raw_root,
            "private_evidence_root": private_evidence_root,
        }.items():
            try:
                lexical, resolved, traverses_up = _storage_target(root, value)
            except (OSError, RuntimeError):
                invalid_path_found = True
                continue
            storage_lexical[name] = lexical
            storage_targets[name] = resolved
            traversal_found = traversal_found or traverses_up
        if traversal_found:
            blockers.append("STORAGE_RELATIVE_TRAVERSAL")
        if invalid_path_found or len(storage_targets) != 3:
            blockers.append("STORAGE_PATH_INVALID")
        target_items = list(storage_targets.items())
        overlaps = [
            f"{first_name}/{second_name}"
            for index, (first_name, first_path) in enumerate(target_items)
            for second_name, second_path in target_items[index + 1 :]
            if _paths_overlap(first_path, second_path)
        ]
        unsafe_targets = [
            name for name, path in storage_lexical.items() if path.is_symlink()
        ]
        occupied = [
            name
            for name, path in storage_targets.items()
            if name not in unsafe_targets and _nonempty(path)
        ]
        invalid_parents = [
            name
            for name, path in storage_lexical.items()
            if name not in unsafe_targets and not _directory_can_host_children(path)
        ]
        if overlaps:
            blockers.append("STORAGE_ROOT_OVERLAP")
        if occupied:
            blockers.append("STORAGE_TARGET_NOT_EMPTY")
        if unsafe_targets:
            blockers.append("STORAGE_TARGET_SYMLINK")
        if invalid_parents:
            blockers.append("STORAGE_PARENT_INVALID")

    skill_preview_status = (
        "not-requested"
        if not install_connector
        else (
            "blocked"
            if any(code.startswith("CODEX_SKILL_") for code in blockers)
            else _skill_bundle_status(skill_source, skill_target)
        )
    )
    integration_unverified = install_connector and (
        connector_exists or skill_preview_status == "existing-unverified"
    )
    preview = {
        "schema": "rkf-local-bootstrap-v1",
        "profile": "local-single-machine",
        "mode": "apply" if apply else "preview",
        "status": (
            "blocked"
            if blockers
            else (
                "existing-unverified"
                if workspace_exists or integration_unverified
                else "ready"
            )
        ),
        "blocker_codes": blockers,
        "workspace_config": "existing" if workspace_exists else "would-create",
        "storage": "existing-unverified" if workspace_exists else "would-initialize",
        "writer_registry": "existing-unverified" if workspace_exists else "would-create",
        "connector": (
            "not-requested"
            if not install_connector
            else (
                "blocked"
                if any(code.startswith("CONNECTOR_") for code in blockers)
                else ("existing" if connector_exists else "would-create")
            )
        ),
        "codex_skill": skill_preview_status,
        "secrets_written": False,
        "private_paths_reported": False,
    }
    if not apply:
        return preview
    if blockers:
        raise SystemExit("bootstrap preflight blocked: " + ", ".join(blockers))

    workspace_status = "existing"
    storage_status = "existing-unverified"
    registry_status = "existing-unverified"
    connector_status = "not-requested"
    skill_status = "not-requested"
    created_files: list[tuple[Path, bytes]] = []
    created_dirs: list[Path] = []
    created_skill: Path | None = None
    try:
        if not workspace_exists:
            machine_id = opaque_machine_id()
            config_text = render_workspace_config(
                machine_id=machine_id,
                wiki_root=wiki_root,
                raw_root=raw_root,
                private_evidence_root=private_evidence_root,
            )
            config_bytes = _write_new_text(
                workspace_config,
                config_text,
                created_dirs=created_dirs,
            )
            created_files.append((workspace_config, config_bytes))
            workspace = Workspace(root)
            for path in (
                workspace.paths.sources,
                workspace.paths.evidence_index,
                workspace.paths.gates,
                workspace.paths.reading,
                workspace.paths.search_runs,
                workspace.paths.events,
                workspace.paths.sync_state,
                workspace.paths.knowledge,
                workspace.paths.governance,
                workspace.paths.graph,
                workspace.paths.prompts,
                workspace.paths.raw_root,
                workspace.paths.private_evidence,
            ):
                _mkdir_tracked(path, created_dirs)
            registry = workspace.paths.sync_state / "maintenance-writer.json"
            registry_text = (
                json.dumps(
                    {
                        "schema": "rkf-writer-registry-v1",
                        "machine_id": machine_id,
                        "assigned_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    },
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
                + "\n"
            )
            registry_bytes = _write_new_text(
                registry,
                registry_text,
                created_dirs=created_dirs,
            )
            created_files.append((registry, registry_bytes))
            workspace_status = "created"
            storage_status = "initialized"
            registry_status = "created"

        if install_connector:
            skill_status, skill_created = _install_skill_bundle(
                skill_source,
                skill_target,
                created_dirs=created_dirs,
            )
            if skill_created:
                created_skill = skill_target
            if connector_exists:
                connector_status = "existing"
            elif skill_status in {"created", "existing-matching"}:
                connector_text = render_connector_config(root)
                connector_bytes = _write_new_text(
                    connector,
                    connector_text,
                    created_dirs=created_dirs,
                )
                created_files.append((connector, connector_bytes))
                connector_status = "created"
            else:
                connector_status = "not-created"
        return {
            **preview,
            "status": (
                "existing-unverified"
                if workspace_exists
                or integration_unverified
                or (
                    install_connector
                    and skill_status not in {"created", "existing-matching"}
                )
                else "configured"
            ),
            "workspace_config": workspace_status,
            "storage": storage_status,
            "writer_registry": registry_status,
            "connector": connector_status,
            "codex_skill": skill_status,
        }
    except (OSError, RuntimeError) as error:
        _rollback_created(
            files=created_files,
            dirs=created_dirs,
            skill_target=created_skill,
            skill_source=skill_source,
        )
        raise SystemExit(
            "bootstrap apply failed safely; newly created artifacts were rolled back"
        ) from error
    except BaseException:
        _rollback_created(
            files=created_files,
            dirs=created_dirs,
            skill_target=created_skill,
            skill_source=skill_source,
        )
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=str(REPO_ROOT))
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--install-connector", action="store_true")
    parser.add_argument("--connector-path")
    parser.add_argument("--codex-skill-dir")
    parser.add_argument("--wiki-root", default=".rkf_data/wiki")
    parser.add_argument("--raw-root", default=".rkf_data/raw")
    parser.add_argument("--private-evidence-root", default=".rkf_private/evidence")
    args = parser.parse_args(argv)
    result = bootstrap_local(
        Path(args.repo_root),
        apply=args.apply,
        install_connector=args.install_connector,
        connector_path=Path(args.connector_path).expanduser() if args.connector_path else None,
        codex_skill_dir=Path(args.codex_skill_dir).expanduser() if args.codex_skill_dir else None,
        wiki_root=args.wiki_root,
        raw_root=args.raw_root,
        private_evidence_root=args.private_evidence_root,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
